import Head from 'next/head'
import { useFormik } from 'formik'
import * as yup from 'yup'
import { useRouter } from 'next/router'
import {motion as m} from 'framer-motion'

export default function Home() {
  // Router
  const router = useRouter()

  // Logic for formik to store user inputs
  const formik = useFormik({
    initialValues: {
      name: '',
      email: '',
      country: 'Australia',
      terms: ''
    },
    // for validation
    validationSchema: yup.object({
      name: yup.string().max(20, 'name must be 20 characters or less').required('name is required'),
      email: yup.string().email('invalid email address').required('email is required'),
      terms: yup.array().required('please check terms and conditions')
    }),
    onSubmit: (values) => {
      router.push({
        pathname: '/success',
        query: values
      })
    }
  })

  return (
    <m.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='h-screen flex justify-center items-center'>
        <form className='bg-white rounded-lg w-1/2' autoComplete='off'>
          <div className='text-gray-700 p-16'>
            <h1 className='text-3xl font-bold pb-2'>
              Let's get started
            </h1>
            <p className='text-lg text-gray-500'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia magnam illum expedita enim ducimus dignissimos?
            </p>

            <div className='mt-6'>

              {/* name input field */}
              <div className="pb-4">
                <label htmlFor="name" 
                  className={`block text-sm pb-2 ${formik.touched.name && formik.errors.name ? 'text-red-400' : ''}`}
                >
                  {
                    formik.touched.name && formik.errors.name ? formik.errors.name: 'Name'
                  }
                </label>
                <input 
                  type="text" 
                  name="name"
                  placeholder='Enter your name...' 
                  value={formik.values.name}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  className='border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500'
                />
              </div>

              {/* email input field */}
              <div className="pb-4">
                <label 
                  htmlFor="email" 
                  className={`block text-sm pb-2 ${formik.touched.email && formik.errors.email ? 'text-red-400' : ''}`}
                >
                  {
                    formik.touched.email && formik.errors.email ? formik.errors.email: 'Email'
                  }
                </label>
                <input 
                  type="email" 
                  name="email"
                  placeholder='Enter your email...' 
                  value={formik.values.email}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  className='border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500'
                />
              </div>

              {/* select input field */}
              <div className="pb-4">
                <label 
                  htmlFor="country" 
                  className={`block text-sm pb-2 ${formik.errors.country ? 'text-red-400' : ''}`}
                >
                  Country
                </label>
                <select 
                  name="country" 
                  className='border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500'
                  value={formik.values.country}
                  onChange={formik.handleChange}
                >
                  <option>United Kingdom</option>
                  <option>United Arab Emirates</option>
                  <option>Australia</option>
                  <option>Newzeland</option>
                </select>
              </div>

              {/* checkbox input field */}
              <div className="pb-4">
                <label 
                  htmlFor="terms" 
                  className={`block text-sm pb-2 ${formik.touched.terms && formik.errors.terms ? 'text-red-400' : ''}`}
                >
                  {
                    formik.touched.terms && formik.errors.terms ? formik.errors.terms: 'Terms of service'
                  }
                </label>
                <div className='flex items-center gap-2'>
                  <input 
                    type="checkbox" 
                    name="terms"
                    value='checked'
                    // value={formik.values.terms}
                    onChange={formik.handleChange}
                    onBlur={formik.handleBlur}
                    className='h-5 w-5 text-teal-500 border-2 focus:border-teal-500 focus:ring-teal-500'
                  />
                  <p className='text-sm text-gray-500'>
                    I agree to terms and conditions that my data will be secured.
                  </p>
                </div>
              </div>

              <button 
                type='submit' 
                className='bg-teal-500 text-white text-sm py-3 mt-6 rounded-lg w-full'
                onClick={formik.handleSubmit}
              >
                Start learning today!
              </button>
            </div>
          </div>
        </form>
      </main>
    </m.div>
  )
}
